chore: adapt license and readme
linuxdeepin/deepin-fcitxconfigtool-plugin pull request #35
Opened 2022-09-08 03:39 UTC by guonafu

Description: open source  compliance rectification

Log: Change readme and license to SPDX rule

2022-09-08 07:02 UTC, BLumia requested changes

2022-09-08 07:02 UTC, BLumia commented on .reuse/dep5
> +# License: ...
```suggestion
```

2022-09-08 07:02 UTC, BLumia commented on .reuse/dep5
> +Copyright: None
CC-BY 署名署 None 不对吧？

2022-09-08 07:02 UTC, BLumia commented on .reuse/dep5
> +Files: *.sh
要么标上完整路径，要么在 .sh 文件里加注释声明著作权和许可（如果是我们第一方的脚本的话）

2022-09-08 07:02 UTC, BLumia commented on README_zh_CN.md
> +改项目在GPL-3.0-or-later]下发布。
```suggestion

该项目在GPL-3.0-or-later下发布。
```

2022-09-09 05:22 UTC, BLumia submitted a review, later dismissed

2022-09-09 05:22 UTC, BLumia commented on .reuse/dep5
> +License: CC0-1.0
这个应该不用写，可以考虑加个提交删掉。机器人会报这个是因为机器人会生成这个文件。

2022-09-09 06:02 UTC, shao-jun approved these changes

2022-09-09 06:03 UTC, BLumia approved these changes

2022-09-09 06:10 UTC, merged